# git has a different opinion of line endings than rubocop
# line endings are converted to match the system on pull/push
Layout/EndOfLine:
  Enabled: false

# No opinion of this style at this time
Style/StringLiterals:
  Enabled: false

# Good code standards and naming conventions are often better
# than unneccesary documentation.
Style/Documentation:
  Enabled: false