version: '3'
services:
  mongo_db:
    image: mongo
    ports: 
      - "27017:27017"
    volumes: 
      - mongo-development-data:/data/db
  web:
    build: .
    image: labrat/trivia:debug
    command: bundle exec bin/rails s -p 3000 -b '0.0.0.0' -e development
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
      - "1234:1234"
      - "26162:26162"
    depends_on:
      - mongo_db
volumes: 
  mongo-development-data: